#!/bin/sh
set -e

case "$1" in
	remove)
		groupdel quickio || true
		userdel quickio || true
	;;
	
	purge)
		# Handled by remove
	;;
	
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#