.\" Manpage for Quick.IO
.TH man 1 "17 July 2013" "0.1" "quickio man page"

.SH NAME
quickio \- run the quickio server

.SH SYNOPSIS
quickio

.SH DESCRIPTION
QuickIO is a simple, fast, and difficult WebSocket server that focuses on being as fast as possible.

.SH OPTIONS

.TP
\fB\--config-file, \-c\fR
Configuration file to load; if not specified, will look in the current directory. This option may be given multiple times to load multiple files.

.TP
\fB\--config-dir, \-d\fR
Configuration directory to scan for other config files. Looks for "*.ini".

.SH BUGS
Report bugs at: https://github.com/iheartradio/quick.io/issues

.SH AUTHOR
Andrew Stone <andrew@clovar.com>
