.\" Manpage for Quick.IO
.TH man 1 "11 April 2014" "0.2.0" "quickio-clienttest"

.SH NAME
quickio-clienttest \- test client implementations against a QuickIO server

.SH SYNOPSIS
quickio-clienttest

.SH DESCRIPTION
Runs a QuickIO server with the quickio-clienttest application loaded. Makes
integration testing with clients a rather simple affair.

.SH BUGS
Report bugs at: https://github.com/iheartradio/quick.io/issues

.SH AUTHOR
Andrew Stone <andrew@clovar.com>
