.\" Manpage for Quick.IO
.TH man 1 "11 April 2014" "0.2.0" "quickio"

.SH NAME
quickio - run a QuickIO server

.SH SYNOPSIS
quickio [-c /etc/quickio/quickio.ini] [-v]

.SH DESCRIPTION
QuickIO is a simple, fast, and difficult WebSocket server that focuses on being as fast as possible.

.SH OPTIONS

.TP
\fB\--config-file, \-f\fR
Configuration file to load. This option may be given multiple times to load
multiple files; it understands most common globbing patterns.

.TP
\fB\--version, \-v\fR
Get the server version

.SH BUGS
Report bugs at: https://github.com/iheartradio/quick.io/issues

.SH AUTHOR
Andrew Stone <andrew@clovar.com>
