.\" Manpage for Quick.IO
.TH man 1 "3 April 2013" "1.0" "quickio man page"

.SH NAME
quickio \- run the quickio server

.SH SYNOPSIS
quickio

.SH DESCRIPTION
QuickIO is a simple, fast, and difficult WebSocket server that focuses on being as fast as possible.

.SH OPTIONS

.TP
\fB\--config-file, \-c\fR
an absolute path to the quickio.ini configuration file

.SH BUGS
Report bugs at: https://github.com/iheartradio/quick.io/issues

.SH AUTHOR
Andrew Stone <andrew@clovar.com>
