.\" Manpage for Quick.IO
.TH man 1 "11 April 2014" "0.2.0" "quickio-clienttest"

.SH NAME
quickio-clienttest \- test client implementations against a QuickIO server

.SH SYNOPSIS
quickio-clienttest

.SH DESCRIPTION
Runs a QuickIO server with the quickio-clienttest application loaded. Makes
integration testing with clients a rather simple affair.

By default, runs on port 55440. If running as root, also listens on port 843
for flash connections.

To test client that clients fallback to HTTP, use port 55441: it rewrites
the HTTP headers to be invalid in much the same way proxies do. If your tests
fail sporadically, then you are not handling all possible error cases.

.SH BUGS
Report bugs at: https://github.com/iheartradio/quick.io/issues

.SH AUTHOR
Andrew Stone <andrew@clovar.com>
