#!/usr/bin/env python
#
# Run QuickIO so that the fuzzer can hit it.

import exceptions
import os
import multiprocessing
import resource
import subprocess
import sys

INI_FILE = '/tmp/quickio-fuzzer.%d.ini' % os.getpid()
INI = '''[quick-event]
max-clients = %d
threads = %d
[quick.io]
bind-address = 0.0.0.0
bind-port = 8080
bind-path = /tmp/quickio.sock
public-address = localhost
'''

if "/usr/bin" in os.path.abspath(__file__):
	qio_path = "quickio"
else:
	qio_path = "./quickio"

with open(INI_FILE, 'w') as f:
	f.write(INI % (
		resource.getrlimit(resource.RLIMIT_NOFILE)[0],
		multiprocessing.cpu_count(),
	))

try:
	ret = subprocess.call([qio_path, '--config-file=%s' % INI_FILE])
	if ret != 0:
		raise Exception('QuickIO exited with status %d' % ret)
except exceptions.KeyboardInterrupt:
	pass
except OSError as e:
	print >> sys.stderr, 'Error executing quickio: %s' % e
	sys.exit(1)
except:
	print >> sys.stderr, 'Error: %s' % sys.exc_info()[1]
	sys.exit(1)
finally:
	os.remove(INI_FILE)
